version: '2'

services:
  subsonic:
    image: vidiben/subsonic
    container_name: subsonic
    restart: always
    ports:
      - "4040:4040"
    volumes:
      - ${HOME}/zik:/var/subsonic/music:ro
      - ${HOME}/.config/subsonic:/var/subsonic/data
